# Generated by Django 5.1.1 on 2024-10-06 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specification', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specification', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_service', models.DateField()),
                ('working_hours', models.FloatField()),
                ('order_No', models.CharField(max_length=100)),
                ('date_order', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specification', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_failure', models.CharField(max_length=250)),
                ('working_hours', models.FloatField()),
                ('description_of_failure', models.TextField()),
                ('spare_parts', models.TextField(blank=True)),
                ('date_of_restoration', models.CharField(max_length=100)),
                ('downtime', models.CharField(max_length=100)),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviceApp.failurenode')),
            ],
        ),
    ]
