# Generated by Django 5.1.1 on 2024-10-06 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('specification', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Узел отказа',
                'verbose_name_plural': 'Узлы отказа',
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('specification', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Способ восстановления',
                'verbose_name_plural': 'Способы восстановления',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_service', models.DateField(verbose_name='дата проведения ТО')),
                ('working_hours', models.FloatField(verbose_name='наработка, м/час')),
                ('order_No', models.CharField(max_length=100, verbose_name='№ заказ-наряда')),
                ('date_order', models.DateField(verbose_name='дата заказ-наряда')),
            ],
            options={
                'verbose_name': 'ТО',
                'verbose_name_plural': 'ТО',
            },
        ),
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('specification', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Вид ТО',
                'verbose_name_plural': 'Виды ТО',
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_failure', models.CharField(max_length=250, verbose_name='дата отказа')),
                ('working_hours', models.FloatField(verbose_name='наработка, м/час')),
                ('description_of_failure', models.TextField(verbose_name='описание отказа')),
                ('spare_parts', models.TextField(blank=True, verbose_name='используемые запасные части')),
                ('date_of_restoration', models.CharField(max_length=100, verbose_name='дата восстановления')),
                ('downtime', models.CharField(max_length=100, verbose_name='время простоя техники')),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviceApp.failurenode', verbose_name='узел отказа')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
            },
        ),
    ]
