# Generated by Django 5.1.1 on 2024-10-06 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceApp', '0001_initial'),
        ('silantApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silantApp.machine', verbose_name='машина'),
        ),
    ]
