# Generated by Django 5.1.1 on 2024-10-29 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceApp', '0002_initial'),
        ('silantApp', '0001_initial'),
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usersApp.serviseorganization', verbose_name='сервисная компания'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='recovery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviceApp.recoverymethod', verbose_name='способ восстановления'),
        ),
        migrations.AddField(
            model_name='service',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silantApp.machine', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.serviseorganization', verbose_name='сервисная компания'),
        ),
        migrations.AddField(
            model_name='service',
            name='type_of_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviceApp.typeofservice', verbose_name='Вид ТО'),
        ),
    ]
