# Generated by Django 5.1.1 on 2024-10-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='downtime',
            field=models.FloatField(blank=True, null=True, verbose_name='время простоя техники в днях'),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_order',
            field=models.DateField(blank=True, null=True, verbose_name='дата заказ-наряда'),
        ),
    ]
