# Generated by Django 5.1.1 on 2024-10-06 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specification', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrivingAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specification', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specification', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelOfAControlledBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specification', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('specification', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specification', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=120)),
                ('serial_num', models.CharField(max_length=120, unique=True)),
                ('engine_num', models.CharField(max_length=120)),
                ('transmission_num', models.CharField(max_length=120)),
                ('driving_axle_num', models.CharField(max_length=120)),
                ('num_of_a_controlled_bridge', models.CharField(max_length=120)),
                ('contractNo', models.CharField(max_length=120, unique=True)),
                ('consignee', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('equipment', models.CharField(blank=True, max_length=255)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silantApp.carmodel')),
            ],
        ),
    ]
