# Generated by Django 5.1.1 on 2024-10-06 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('silantApp', '0001_initial'),
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.client'),
        ),
        migrations.AddField(
            model_name='machine',
            name='driving_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silantApp.drivingaxlemodel'),
        ),
        migrations.AddField(
            model_name='machine',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silantApp.enginemodel'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_of_a_controlled_bridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silantApp.modelofacontrolledbridge'),
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silantApp.servicecompany'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silantApp.transmissionmodel'),
        ),
    ]
