# Generated by Django 5.1.1 on 2024-10-29 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('silantApp', '0001_initial'),
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='machine',
            name='driving_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silantApp.drivingaxlemodel', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silantApp.enginemodel', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usersApp.serviseorganization', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_of_a_controlled_bridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silantApp.modelofacontrolledbridge', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silantApp.transmissionmodel', verbose_name='Модель трансмиссии'),
        ),
    ]
